/* cases.js — case definitions: clues, suspects, dialogue, solutions */

const CASES = [
  {
    id: 'museum_heist',
    title: 'The Museum Heist',
    briefing: 'A priceless painting has vanished from the East Wing of the Grand Gallery. Security cameras caught nothing. The thief is still among the visitors. Find them before they slip away.',
    scene: {
      type: 'museum',
      characterSlots: 18,
    },
    culprit: {
      hat: 'beret',
      hatColor: '#8B0000',
      glasses: true,
      holdingItem: 'tube',
    },
    clues: [
      { text: 'Witnesses say the thief wore a dark red beret', attribute: 'hat', value: 'beret' },
      { text: 'Security noticed someone with glasses near the painting', attribute: 'glasses', value: true },
      { text: 'A cylindrical object was seen being carried out', attribute: 'holdingItem', value: 'tube' },
      { text: 'A guard recalls seeing a blue coat in the area', type: 'redHerring' },
      { text: 'The suspect was last seen near the east wall', type: 'flavor' },
    ],
    solution: 'The art student with the beret and painting tube!',
  },
  {
    id: 'missing_recipe',
    title: 'The Missing Recipe',
    briefing: "Chef Bernard's legendary soufflé recipe has disappeared from the kitchen safe. One of the staff took it. The kitchen is chaos \u2014 find the thief before service starts.",
    scene: {
      type: 'kitchen',
      characterSlots: 16,
    },
    culprit: {
      hat: 'cap',
      hatColor: '#e6edf3',
      holdingItem: 'book',
      accessory: 'badge',
      shirtColor: '#e6edf3',
    },
    clues: [
      { text: 'The recipe was in a small leather-bound book', attribute: 'holdingItem', value: 'book' },
      { text: 'Only staff wear ID badges in the kitchen', attribute: 'accessory', value: 'badge' },
      { text: "They were wearing a white chef's cap", attribute: 'hat', value: 'cap' },
      { text: 'Someone mentioned seeing red shoes near the exit', type: 'redHerring' },
    ],
    solution: "The kitchen porter with the chef's cap, badge, and recipe book!",
  },
  {
    id: 'library_whisper',
    title: 'The Library Whisper',
    briefing: 'A rare first edition has been slipped off the shelf and hidden somewhere in the reading room. The librarian noticed it missing during the afternoon check. The culprit is still here, pretending to read.',
    scene: {
      type: 'library',
      characterSlots: 18,
    },
    culprit: {
      glasses: false,
      holdingItem: 'bag',
      facialHair: 'mustache',
      shirtColor: '#484f58',
    },
    clues: [
      { text: 'The suspect was NOT wearing glasses \u2014 unusual for a bookworm', attribute: 'glasses', value: false },
      { text: 'They had a large bag \u2014 big enough to hide a book', attribute: 'holdingItem', value: 'bag' },
      { text: 'A distinctive mustache was noticed', attribute: 'facialHair', value: 'mustache' },
      { text: 'They were sitting near the window', type: 'flavor' },
      { text: 'Someone saw a person in green leave the rare books section', type: 'redHerring' },
    ],
    solution: 'The mustachioed patron with the large bag \u2014 no glasses, just audacity!',
  },
  {
    id: 'park_thief',
    title: 'The Vanishing Violinist',
    briefing: 'The city park\'s beloved street violinist has vanished mid-performance, along with a priceless Stradivarius on loan from the conservatory. The crowd saw nothing \u2014 but the thief is still here, hiding the instrument. Search the park before they disappear into the evening.',
    scene: {
      type: 'park',
      characterSlots: 16,
    },
    culprit: {
      hat: 'cap',
      holdingItem: 'bag',
      glasses: false,
    },
    clues: [
      { text: 'The thief stuffed the violin into a large bag', attribute: 'holdingItem', value: 'bag' },
      { text: 'A jogger saw someone in a cap fleeing the bandstand', attribute: 'hat', value: 'cap' },
      { text: 'The suspect was NOT wearing glasses', attribute: 'glasses', value: false },
      { text: 'Someone in a red jacket was seen near the fountain', type: 'redHerring' },
    ],
    solution: 'The cap-wearing park-goer with the suspiciously bulging bag \u2014 no glasses, all guilt!',
  },
  {
    id: 'train_heist',
    title: 'The Midnight Express',
    briefing: 'A diplomatic courier\'s briefcase containing classified documents was snatched on Platform 9 just as the midnight express pulled in. The station is sealed. The thief is among the travelers \u2014 find them before the next train departs.',
    scene: {
      type: 'train_station',
      characterSlots: 18,
    },
    culprit: {
      hat: 'tophat',
      shirtColor: '#484f58',
      holdingItem: 'briefcase',
    },
    clues: [
      { text: 'The thief was carrying a leather briefcase', attribute: 'holdingItem', value: 'briefcase' },
      { text: 'A porter noticed someone in a top hat near the courier', attribute: 'hat', value: 'tophat' },
      { text: 'They wore a dark-colored shirt', attribute: 'shirtColor', value: '#484f58' },
      { text: 'A woman with a red scarf was arguing at the ticket booth', type: 'redHerring' },
      { text: 'The suspect was last seen heading toward Platform 3', type: 'flavor' },
    ],
    solution: 'The gentleman in the top hat and dark shirt, clutching the stolen briefcase!',
  },
  {
    id: 'hotel_diamond',
    title: 'The Diamond Suite',
    briefing: 'A flawless 40-carat diamond has vanished from the penthouse suite\'s private safe. The hotel is on lockdown. Every guest in the lobby is a suspect. The thief is brazen enough to still be wearing their prize. Find them.',
    scene: {
      type: 'hotel_lobby',
      characterSlots: 20,
    },
    culprit: {
      glasses: true,
      accessory: 'necklace',
      holdingItem: 'bag',
    },
    clues: [
      { text: 'The diamond was likely hidden in a bag for transport', attribute: 'holdingItem', value: 'bag' },
      { text: 'A bellhop saw someone with glasses near the elevator', attribute: 'glasses', value: true },
      { text: 'The thief was spotted wearing a distinctive necklace', attribute: 'accessory', value: 'necklace' },
      { text: 'Room service saw someone in a green coat leaving floor 12', type: 'redHerring' },
      { text: 'The concierge remembers a guest asking about gemstone appraisals', type: 'flavor' },
    ],
    solution: 'The bespectacled guest with the necklace and bag \u2014 diamonds are not just forever, they\'re portable!',
  },
  {
    id: 'market_poison',
    title: 'The Poisoned Pear',
    briefing: 'A rival merchant has been poisoning fruit at the morning market, sending three vendors to the hospital. The poison was traced to a single saboteur working the crowd. They\'re still out there among the shoppers. Find them before the market closes.',
    scene: {
      type: 'market',
      characterSlots: 18,
    },
    culprit: {
      hat: 'cap',
      facialHair: 'mustache',
      holdingItem: 'bag',
    },
    clues: [
      { text: 'The poisoner carried a bag \u2014 likely containing the toxin', attribute: 'holdingItem', value: 'bag' },
      { text: 'A fruit seller noticed a man with a mustache lingering too long', attribute: 'facialHair', value: 'mustache' },
      { text: 'They were wearing a cap pulled low over their eyes', attribute: 'hat', value: 'cap' },
      { text: 'Someone in blue overalls was seen handling the pear crates', type: 'redHerring' },
      { text: 'The suspect bought nothing but touched everything', type: 'flavor' },
    ],
    solution: 'The mustachioed man in the cap, bag full of poison \u2014 rotten to the core!',
  },
  {
    id: 'theater_phantom',
    title: 'The Phantom\'s Encore',
    briefing: 'During the final act of the opera, the lead soprano\'s legendary voice was silenced \u2014 someone switched her throat spray with a numbing agent. The saboteur is in the audience, blending in with the theater crowd. The show must go on, but first: find the phantom.',
    scene: {
      type: 'theater',
      characterSlots: 20,
    },
    culprit: {
      hat: null,
      glasses: true,
      shirtColor: '#1a1a1a',
      holdingItem: 'flower',
    },
    clues: [
      { text: 'The phantom wore NO hat \u2014 unusual for opening night', attribute: 'hat', value: null },
      { text: 'They wore glasses and watched the soprano intently', attribute: 'glasses', value: true },
      { text: 'The suspect was dressed in all black', attribute: 'shirtColor', value: '#1a1a1a' },
      { text: 'They carried a single flower \u2014 perhaps a calling card', attribute: 'holdingItem', value: 'flower' },
      { text: 'An usher saw someone with a gold watch in Row C', type: 'redHerring' },
    ],
    solution: 'The bespectacled figure in black, hatless and holding a single flower \u2014 the phantom takes a bow!',
  },
  {
    id: 'office_leak',
    title: 'The Corporate Leak',
    briefing: 'Classified merger documents have been photographed and leaked to a competitor. The security breach happened during lunch hour. IT traced the leak to someone on this floor. The mole is still at their desk, pretending nothing happened.',
    scene: {
      type: 'office',
      characterSlots: 16,
    },
    culprit: {
      glasses: true,
      accessory: 'badge',
      holdingItem: 'phone',
    },
    clues: [
      { text: 'The mole used their phone to photograph the documents', attribute: 'holdingItem', value: 'phone' },
      { text: 'Security footage shows someone with glasses near the file room', attribute: 'glasses', value: true },
      { text: 'Only badged employees had access to the secure floor', attribute: 'accessory', value: 'badge' },
      { text: 'A colleague saw someone in a red tie near the shredder', type: 'redHerring' },
    ],
    solution: 'The badge-wearing employee with glasses, phone still in hand \u2014 caught red-handed!',
  },
  {
    id: 'gallery_forgery',
    title: 'The Perfect Forgery',
    briefing: 'A masterwork has been swapped with a forgery at the Modern Art Gallery. The switch happened during today\'s private viewing. The forger is still mingling with guests, carrying the original rolled in a tube. Art lovers and criminals look the same here \u2014 use the clues wisely.',
    scene: {
      type: 'gallery',
      characterSlots: 18,
    },
    culprit: {
      hat: 'beret',
      holdingItem: 'tube',
      facialHair: null,
    },
    clues: [
      { text: 'The forger carried the stolen painting in a cylindrical tube', attribute: 'holdingItem', value: 'tube' },
      { text: 'An art critic noticed someone in a beret studying the frame closely', attribute: 'hat', value: 'beret' },
      { text: 'The suspect had no facial hair \u2014 a clean-shaven professional', attribute: 'facialHair', value: null },
      { text: 'Gallery security mentioned someone in purple shoes pacing nervously', type: 'redHerring' },
      { text: 'A guest overheard someone saying "the brushwork is almost too perfect"', type: 'redHerring' },
    ],
    solution: 'The clean-shaven artist in the beret, painting tube under their arm \u2014 forgery is an art too, apparently!',
  },
  {
    id: 'cafe_cipher',
    title: 'The Espresso Code',
    briefing: 'A coded message was slipped into the wrong coffee cup at the Corner Caf\u00e9 \u2014 a dead drop gone wrong. The message contains coordinates to a hidden weapons cache. The courier realized the mistake and is still here, nursing a drink and waiting for a chance to retrieve it. Find them before they vanish.',
    scene: {
      type: 'cafe',
      characterSlots: 14,
    },
    culprit: {
      glasses: false,
      holdingItem: 'cup',
      hat: 'beanie',
    },
    clues: [
      { text: 'The courier is still holding a coffee cup \u2014 waiting for the swap', attribute: 'holdingItem', value: 'cup' },
      { text: 'They were NOT wearing glasses \u2014 no disguise today', attribute: 'glasses', value: false },
      { text: 'A barista remembers a beanie-wearing regular acting strangely', attribute: 'hat', value: 'beanie' },
      { text: 'Someone with a laptop bag was typing furiously near the window', type: 'redHerring' },
      { text: 'The suspect ordered a double espresso, no milk', type: 'flavor' },
    ],
    solution: 'The beanie-clad coffee drinker with no glasses \u2014 the code was in the cup all along!',
  },
  {
    id: 'harbor_smuggler',
    title: 'The Harbor Fog',
    briefing: 'Under cover of the morning fog, a shipment of stolen antiquities was unloaded at the harbor. Customs intercepted the manifest but the smuggler slipped onto the docks. They\'re hiding in plain sight among the dockworkers and fishermen. The fog is lifting \u2014 find them now.',
    scene: {
      type: 'harbor',
      characterSlots: 18,
    },
    culprit: {
      hat: 'cap',
      holdingItem: 'bag',
      shirtColor: '#484f58',
    },
    clues: [
      { text: 'The smuggler carried a heavy bag \u2014 full of contraband', attribute: 'holdingItem', value: 'bag' },
      { text: 'A fisherman spotted someone in a cap near the cargo hold', attribute: 'hat', value: 'cap' },
      { text: 'They wore a dark shirt to blend with the dock crew', attribute: 'shirtColor', value: '#484f58' },
      { text: 'A harbor patrol saw someone in yellow boots running toward Pier 7', type: 'redHerring' },
      { text: 'The lighthouse keeper reported a flashing signal at 3 AM', type: 'redHerring' },
    ],
    solution: 'The dark-shirted figure in a cap, bag heavy with stolen treasures \u2014 anchors aweigh, smuggler!',
  },
  {
    id: 'garden_secret',
    title: 'The Garden Conspiracy',
    briefing: 'During the annual garden party at the Whitmore Estate, a secret treaty was stolen from the host\'s private study. The thief returned to the party as if nothing happened. With 20 guests milling among the hedges and roses, you\'ll need sharp eyes. The conspirator is hiding behind good manners.',
    scene: {
      type: 'garden',
      characterSlots: 20,
    },
    culprit: {
      hat: null,
      holdingItem: 'umbrella',
      accessory: 'scarf',
      glasses: true,
    },
    clues: [
      { text: 'The thief carried an umbrella despite the clear weather \u2014 suspicious', attribute: 'holdingItem', value: 'umbrella' },
      { text: 'They wore a distinctive scarf as a fashion statement', attribute: 'accessory', value: 'scarf' },
      { text: 'The suspect wore glasses and studied the garden map closely', attribute: 'glasses', value: true },
      { text: 'They wore NO hat \u2014 bold for a garden party', attribute: 'hat', value: null },
      { text: 'A gardener mentioned someone in white gloves near the study window', type: 'redHerring' },
      { text: 'The host\'s dog was barking at a person near the gazebo', type: 'redHerring' },
    ],
    solution: 'The hatless, bespectacled guest with the scarf and unnecessary umbrella \u2014 conspiracy uncovered!',
  },
  {
    id: 'ballroom_murder',
    title: 'The Waltz of Shadows',
    briefing: 'At the Governor\'s masquerade ball, the host was found slumped in his chair \u2014 poisoned. The toxin was slipped into his champagne during the waltz. With 22 masked guests swirling across the dance floor, finding the killer is like finding a needle in a chandelier. But the mask is off now \u2014 look for the clues.',
    scene: {
      type: 'ballroom',
      characterSlots: 22,
    },
    culprit: {
      facialHair: 'beard',
      hat: 'tophat',
      glasses: false,
      holdingItem: 'cup',
    },
    clues: [
      { text: 'The poisoner had a full beard \u2014 hard to miss, even at a masquerade', attribute: 'facialHair', value: 'beard' },
      { text: 'They wore a top hat to the ball', attribute: 'hat', value: 'tophat' },
      { text: 'The killer was NOT wearing glasses', attribute: 'glasses', value: false },
      { text: 'They were still holding a cup \u2014 perhaps their own untainted drink', attribute: 'holdingItem', value: 'cup' },
      { text: 'A waiter recalled someone in a velvet cape near the punch bowl', type: 'redHerring' },
      { text: 'The pianist noticed a guest with a gold monocle watching the host', type: 'redHerring' },
    ],
    solution: 'The bearded gentleman in the top hat, no glasses, cup still in hand \u2014 the waltz of shadows ends here!',
  },
  {
    id: 'lab_experiment',
    title: 'The Missing Formula',
    briefing: 'Dr. Nakamura\'s breakthrough formula for a revolutionary energy catalyst has been stolen from the research lab. The formula was written in a single notebook that vanished during the shift change. The thief is one of the researchers still on the floor. Science waits for no one \u2014 find the thief.',
    scene: {
      type: 'lab',
      characterSlots: 16,
    },
    culprit: {
      glasses: true,
      hat: null,
      holdingItem: 'book',
      accessory: 'badge',
    },
    clues: [
      { text: 'The formula was in a notebook \u2014 the thief is carrying a book', attribute: 'holdingItem', value: 'book' },
      { text: 'Only badged researchers had access to Dr. Nakamura\'s bench', attribute: 'accessory', value: 'badge' },
      { text: 'Security cameras caught someone with glasses near the locked drawer', attribute: 'glasses', value: true },
      { text: 'The suspect wore NO hat \u2014 lab protocol', attribute: 'hat', value: null },
      { text: 'A lab tech mentioned someone in a green coat leaving the chemical storage', type: 'redHerring' },
      { text: 'The centrifuge was left running by someone who seemed distracted', type: 'redHerring' },
    ],
    solution: 'The hatless, bespectacled researcher with the badge and stolen notebook \u2014 the formula is recovered!',
  },
];
